// Auto-generated by tools/scrape_linkedin_badge.py — do not edit by hand.
// Identity + company config for what the badge displays.
#pragma once

#define BADGE_NAME "Marcus Greenwood"
#define BADGE_TITLE "CEO"
#define BADGE_COMPANY "UBIO"
#define BADGE_COMPANY_LINE BADGE_TITLE " @ " BADGE_COMPANY
#define BADGE_URL "https://cal.com/marcusgreenwood/15min"
