#!/usr/bin/env python3
"""Capture a3-platform Loading.vue dash animation and bake badge frames.

Sets stroke-dasharray / stroke-dashoffset with the same keyframe lerp as
Loading.vue (not CSS animation-delay seeking), screenshots Chromium, and
writes ConferenceBadge/a3_frames.h plus a preview GIF/MP4.
"""

from __future__ import annotations

import http.server
import socketserver
import subprocess
import threading
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
TOOLS = Path(__file__).resolve().parent
OUT_DIR = ROOT / "ConferenceBadge"
FRAMES_DIR = ROOT / "screenshots" / "a3-loading"
HEADER = OUT_DIR / "a3_frames.h"

# Flash budget: 2-bit 200² × 48 ≈ 480 KB.
FRAME_PX = 200
BADGE_FRAMES = 48
# Preview GIF/MP4: dense samples so the stroke motion isn't choppy.
# Slowed 40s cycle, captured realtime at 30fps.
PREVIEW_FRAMES = 1200
PREVIEW_FPS = 30.0
SOURCE_SECS = 40.0


def start_server() -> tuple[socketserver.TCPServer, str]:
    class Handler(http.server.SimpleHTTPRequestHandler):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, directory=str(TOOLS), **kwargs)

        def log_message(self, fmt, *args):
            pass

    httpd = socketserver.TCPServer(("127.0.0.1", 0), Handler)
    thread = threading.Thread(target=httpd.serve_forever, daemon=True)
    thread.start()
    port = httpd.server_address[1]
    return httpd, f"http://127.0.0.1:{port}/a3_loading.html"


def crop_logo(img: Image.Image, pad: int = 8) -> Image.Image:
    """Tight crop around non-white pixels so the mark fills the badge disc."""
    img = img.convert("RGB")
    pix = img.load()
    w, h = img.size
    min_x, min_y, max_x, max_y = w, h, 0, 0
    found = False
    for y in range(h):
        for x in range(w):
            r, g, b = pix[x, y]
            if r < 250 or g < 250 or b < 250:
                found = True
                if x < min_x:
                    min_x = x
                if y < min_y:
                    min_y = y
                if x > max_x:
                    max_x = x
                if y > max_y:
                    max_y = y
    if not found:
        return img
    min_x = max(0, min_x - pad)
    min_y = max(0, min_y - pad)
    max_x = min(w - 1, max_x + pad)
    max_y = min(h - 1, max_y + pad)
    # Keep square crop centered on the content.
    side = max(max_x - min_x + 1, max_y - min_y + 1)
    cx = (min_x + max_x) / 2
    cy = (min_y + max_y) / 2
    x0 = int(round(cx - side / 2))
    y0 = int(round(cy - side / 2))
    x0 = max(0, min(x0, w - side))
    y0 = max(0, min(y0, h - side))
    return img.crop((x0, y0, x0 + side, y0 + side))


def quantize_ink(img: Image.Image) -> list[int]:
    """Map white→indigo coverage to 2-bit levels 0..3."""
    img = img.convert("RGB").resize((FRAME_PX, FRAME_PX), Image.Resampling.LANCZOS)
    pix = img.load()
    levels: list[int] = []
    for y in range(FRAME_PX):
        for x in range(FRAME_PX):
            r, g, b = pix[x, y]
            # How far from white toward indigo ink.
            ink = (255 - r) * 0.25 + (255 - g) * 0.35 + (255 - b) * 0.40
            if ink < 12:
                levels.append(0)
            elif ink < 55:
                levels.append(1)
            elif ink < 120:
                levels.append(2)
            else:
                levels.append(3)
    return levels


def pack_2bit(levels: list[int]) -> bytes:
    out = bytearray((FRAME_PX * FRAME_PX + 3) // 4)
    for i, lev in enumerate(levels):
        out[i >> 2] |= (lev & 3) << ((i & 3) * 2)
    return bytes(out)


def write_header(frames: list[bytes]) -> None:
    n = len(frames)
    bpr = len(frames[0])
    lines = [
        "// Auto-generated by tools/capture_a3_loading.py from Loading.vue CSS.",
        "// 2-bit ink coverage (0=white .. 3=indigo), row-major, 4 pixels/byte LSB.",
        "#pragma once",
        "#include <stdint.h>",
        f"#define A3_FRAME_W {FRAME_PX}",
        f"#define A3_FRAME_H {FRAME_PX}",
        f"#define A3_FRAME_N {n}",
        f"#define A3_FRAME_BYTES {bpr}",
        f"static const uint8_t kA3Frames[{n * bpr}] PROGMEM = {{",
    ]
    blob = b"".join(frames)
    row: list[str] = []
    for i, b in enumerate(blob):
        row.append(f"0x{b:02X}")
        if len(row) == 32:
            lines.append("  " + ",".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ",".join(row) + ",")
    lines.append("};")
    HEADER.write_text("\n".join(lines) + "\n")


def capture() -> None:
    from playwright.sync_api import sync_playwright

    FRAMES_DIR.mkdir(parents=True, exist_ok=True)
    for old in FRAMES_DIR.glob("frame-*.png"):
        old.unlink()

    httpd, url = start_server()
    preview: list[Image.Image] = []
    crop_box: tuple[int, int, int, int] | None = None

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page(
                viewport={"width": 320, "height": 320}, device_scale_factor=3
            )
            page.goto(url, wait_until="networkidle")
            page.wait_for_timeout(100)

            # Solid stroke once → fixed crop so sparse dash frames don't jump.
            page.evaluate(
                """() => {
                  const m = document.getElementById('mark');
                  m.style.strokeDasharray = 'none';
                  m.style.strokeDashoffset = '0';
                }"""
            )
            page.wait_for_timeout(40)
            solid = Image.open(
                __import__("io").BytesIO(
                    page.screenshot(type="png", omit_background=False)
                )
            ).convert("RGB")
            cropped_solid = crop_logo(solid, pad=12)
            # Recover the square crop rectangle by matching size.
            # Recompute box from solid for reuse:
            pix = solid.load()
            w, h = solid.size
            min_x, min_y, max_x, max_y = w, h, 0, 0
            for y in range(h):
                for x in range(w):
                    r, g, b = pix[x, y]
                    if r < 250 or g < 250 or b < 250:
                        min_x = min(min_x, x)
                        min_y = min(min_y, y)
                        max_x = max(max_x, x)
                        max_y = max(max_y, y)
            pad = 12
            min_x = max(0, min_x - pad)
            min_y = max(0, min_y - pad)
            max_x = min(w - 1, max_x + pad)
            max_y = min(h - 1, max_y + pad)
            side = max(max_x - min_x + 1, max_y - min_y + 1)
            cx = (min_x + max_x) / 2
            cy = (min_y + max_y) / 2
            x0 = int(round(cx - side / 2))
            y0 = int(round(cy - side / 2))
            x0 = max(0, min(x0, w - side))
            y0 = max(0, min(y0, h - side))
            crop_box = (x0, y0, x0 + side, y0 + side)
            print(f"fixed crop {crop_box}")

            for i in range(PREVIEW_FRAMES):
                t = SOURCE_SECS * i / PREVIEW_FRAMES
                page.evaluate(f"window.seekLoading({t:.6f})")
                page.wait_for_timeout(20)
                raw = page.screenshot(type="png", omit_background=False)
                path = FRAMES_DIR / f"frame-{i:04d}.png"
                path.write_bytes(raw)
                im = Image.open(path).convert("RGB").crop(crop_box)
                im.save(path)
                preview.append(
                    im.resize((FRAME_PX, FRAME_PX), Image.Resampling.LANCZOS)
                )
                print(f"captured {i + 1}/{PREVIEW_FRAMES} t={t:.2f}s")
            browser.close()
    finally:
        httpd.shutdown()

    # Even subsample of the dense timeline for flash-baked badge frames.
    packed = [
        pack_2bit(
            quantize_ink(
                preview[round(i * (PREVIEW_FRAMES - 1) / (BADGE_FRAMES - 1))]
            )
        )
        for i in range(BADGE_FRAMES)
    ]

    write_header(packed)
    gif = FRAMES_DIR / "a3-loading.gif"
    frame_ms = max(1, int(round(1000.0 / PREVIEW_FPS)))
    preview[0].save(
        gif,
        save_all=True,
        append_images=preview[1:],
        duration=frame_ms,
        loop=0,
        optimize=False,
    )
    mp4 = FRAMES_DIR / "a3-loading.mp4"
    try:
        subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-framerate",
                str(PREVIEW_FPS),
                "-i",
                str(FRAMES_DIR / "frame-%04d.png"),
                "-pix_fmt",
                "yuv420p",
                "-crf",
                "18",
                str(mp4),
            ],
            check=False,
            capture_output=True,
        )
    except OSError:
        pass
    print(f"wrote {HEADER} ({HEADER.stat().st_size} bytes source, {len(packed)} badge frames)")
    print(f"preview {gif} ({PREVIEW_FRAMES} frames @ {PREVIEW_FPS:.0f}fps)")
    if mp4.exists():
        print(f"video {mp4}")


if __name__ == "__main__":
    capture()
