#!/usr/bin/env python3
"""Scrape a public LinkedIn profile and generate ESP32 conference badge assets.

Uses Open Graph meta tags (no login required). Outputs profile.h and photo.h
into ConferenceBadge/ for embedding in the firmware.

Usage:
  python3 tools/scrape_linkedin_badge.py https://www.linkedin.com/in/marcusgreenwood/
"""

from __future__ import annotations

import html
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

try:
    from PIL import Image
except ImportError as exc:
    raise SystemExit("Pillow is required: pip install Pillow") from exc

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "ConferenceBadge"

# Fits a 466px round display with a thin rim for curved name/company text.
PHOTO_SIZE = 390
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
)


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8", errors="replace")


def meta(content: str, prop: str) -> str | None:
    pat = rf'<meta[^>]+property="{re.escape(prop)}"[^>]+content="([^"]*)"'
    m = re.search(pat, content, flags=re.I)
    if not m:
        pat = rf'<meta[^>]+content="([^"]*)"[^>]+property="{re.escape(prop)}"'
        m = re.search(pat, content, flags=re.I)
    return html.unescape(m.group(1)) if m else None


def parse_profile(url: str) -> dict[str, str]:
    html_doc = fetch(url)
    title = meta(html_doc, "og:title") or ""
    image = meta(html_doc, "og:image") or ""
    description = meta(html_doc, "og:description") or ""

    name = title.split(" - ")[0].strip() if title else "Unknown"
    company = ""
    if " - " in title:
        company = title.split(" - ")[1].replace("| LinkedIn", "").strip()
    if not company:
        m = re.search(r"Experience:\s*([^·]+)", description)
        if m:
            company = m.group(1).strip()

    if not image:
        raise SystemExit("Could not find profile photo (og:image)")

    return {"name": name, "company": company or " ", "photo_url": image}


def rgb565_le(r: int, g: int, b: int) -> int:
    # Arduino_Canvas + color565 / draw16bitRGBBitmap expect little-endian RGB565
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def download_photo(url: str) -> Image.Image:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = resp.read()
    from io import BytesIO

    img = Image.open(BytesIO(data)).convert("RGB")
    img = img.resize((PHOTO_SIZE, PHOTO_SIZE), Image.Resampling.LANCZOS)
    return img


def write_profile_h(profile: dict[str, str], url: str, path: Path) -> None:
    name = profile["name"].replace("\\", "\\\\").replace('"', '\\"')
    company = profile["company"].replace("\\", "\\\\").replace('"', '\\"')
    link = url.replace("\\", "\\\\").replace('"', '\\"')
    path.write_text(
        f"""// Auto-generated by tools/scrape_linkedin_badge.py — do not edit by hand.
#pragma once

#define BADGE_NAME "{name}"
#define BADGE_COMPANY "{company}"
#define BADGE_URL "{link}"
""",
        encoding="utf-8",
    )


def write_photo_h(img: Image.Image, path: Path) -> None:
    pixels = img.load()
    words: list[int] = []
    for y in range(PHOTO_SIZE):
        for x in range(PHOTO_SIZE):
            r, g, b = pixels[x, y]
            words.append(rgb565_le(r, g, b))

    lines = [
        "// Auto-generated by tools/scrape_linkedin_badge.py — do not edit by hand.",
        "#pragma once",
        "",
        f"#define PHOTO_W {PHOTO_SIZE}",
        f"#define PHOTO_H {PHOTO_SIZE}",
        "",
        f"static const uint16_t kPhotoRgb565[PHOTO_W * PHOTO_H] PROGMEM = {{",
    ]
    for i in range(0, len(words), 12):
        chunk = words[i : i + 12]
        lines.append("  " + ", ".join(f"0x{w:04X}" for w in chunk) + ",")
    lines.append("};")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    url = sys.argv[1] if len(sys.argv) > 1 else "https://www.linkedin.com/in/marcusgreenwood/"
    print(f"Fetching {url} ...")
    profile = parse_profile(url)
    print(f"  Name:    {profile['name']}")
    print(f"  Company: {profile['company']}")
    print(f"  Photo:   {profile['photo_url'][:72]}...")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    img = download_photo(profile["photo_url"])
    write_profile_h(profile, url, OUT_DIR / "profile.h")
    write_photo_h(img, OUT_DIR / "photo.h")
    print(f"Wrote {OUT_DIR / 'profile.h'} and {OUT_DIR / 'photo.h'}")

    # Also bake a scannable halftone QR (requires tools/.venv with qrcode)
    try:
        from make_halftone_qr import make_halftone_qr, write_header

        ht = make_halftone_qr(url, img, factor=3, out_size=320)
        ht.save(OUT_DIR / "qr_halftone_preview.png")
        write_header(ht, OUT_DIR / "qr_halftone.h")
        print(f"Wrote {OUT_DIR / 'qr_halftone.h'}")
    except Exception as exc:
        print(f"Halftone QR skipped ({exc})")


if __name__ == "__main__":
    main()
